feat: remove quorum for evm
snapshot-labs/sx-ui pull request #474
Opened 2023-03-06 11:56 UTC by j0hnfl0w

Closes: https://github.com/snapshot-labs/sx-ui/issues/468

2023-03-06 14:06 UTC, Sekhmet commented on src/components/Block/SpaceFormVoting.vue
> +    ...(!evmNetworks.includes(props.selectedNetworkId) && {
We need to change `required` too.

2023-03-06 16:28 UTC, Sekhmet requested changes
![image](https://user-images.githubusercontent.com/1968722/223171037-2c36ef60-bef4-4a7d-a239-6e9f7c6d748d.png)

It's impossible to process in this form:
![image](https://user-images.githubusercontent.com/1968722/223171090-ae61c68f-1a1b-44d3-a196-3c4b445af9ba.png)

2023-03-06 16:38 UTC, j0hnfl0w commented
hm, all of it dynamic quorum changes looks ugly, maybe there is a better way. Maybe it can be only temporary solution.

2023-03-06 17:10 UTC, Sekhmet commented
> hm, all of it dynamic quorum changes looks ugly, maybe there is a better way. Maybe it can be only temporary solution.

Maybe we can avoid those ugly changes by enabling additionalProperties on the definition so we can just pass quorum in without worrying about mapping types/data.

2023-03-13 12:39 UTC, j0hnfl0w commented
yep, here will be the same solution

2023-03-13 12:52 UTC, j0hnfl0w commented
@Sekhmet looked again and decided to leave this dynamic staff, we still need to hide quorum from definition

2023-03-13 13:14 UTC, Sekhmet requested changes

2023-03-16 09:29 UTC, Sekhmet commented on src/views/Create.vue
> +    })
This doesn't really work anyway (https://github.com/snapshot-labs/sx-ui/pull/474/files#r1133918323), so let's revert it.

2023-03-17 10:27 UTC, Sekhmet commented on src/views/Create.vue
> +import { getNetwork, evmNetworks } from '@/networks';
Dead import.

2023-03-20 09:43 UTC, Sekhmet approved these changes
tACK

2023-03-20 09:43 UTC, merged